name: Platformer Generated master-push Build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on:
      - ubuntu-latest
    env:
      SERVICE_NAME: ghcr.io/platformercloud/microservices-demo-frontend
      CONTAINER_REGISTRY: ghcr.io
    steps:
      - uses: actions/checkout@v2
      - name: Set Version
        id: event-version
        run: echo ::set-output
          name=SOURCE_TAG::${GITHUB_REF#refs/heads/}-${{github.sha}}
      - name: SonarQube Scan
        uses: kitabisa/sonarqube-action@master
        with:
          host: https://sonarqube.apps.microservice-poc.platformer.cloud
          login: d502bb02c54db957f1993603f101ab3e61a6c672
          projectKey: frontend
          projectBaseDir: src/frontend
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image
        run: docker build --tag
          ${SERVICE_NAME}:${{steps.event-version.outputs.SOURCE_TAG }} --file
          src/frontend/Dockerfile src/frontend
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
            image-ref: $SERVICE_NAME:${{steps.event-version.outputs.SOURCE_TAG }}
            format: 'table'
            exit-code: '1'
            ignore-unfixed: true
            vuln-type: 'os,library'
            severity: 'CRITICAL,HIGH'
      - name: GitHub Image Push
        run: docker push $SERVICE_NAME:${{steps.event-version.outputs.SOURCE_TAG }}
      - name: Platformer Deploy
        uses: platformer-com/build-deploy-action@v1
        with:
          org-id: ${{secrets.ORG_ID_2865014C_418F_4A5D_81B1_3ED64B60AE85}}
          project-id: ${{secrets.PROJECT_ID_2865014C_418F_4A5D_81B1_3ED64B60AE85}}
          token: ${{secrets.AUTOGENERATED_CICD_2865014C_418F_4A5D_81B1_3ED64B60AE85}}
          image-name: ${{env.SERVICE_NAME}}
          tag: ${{steps.event-version.outputs.SOURCE_TAG }}
          container-id: 7d52b503-93e3-45fe-bbd6-911b0bdd53c9
